title: 技术前沿
description: 关注科技与创新
theme: jekyll-theme-modernist
future: true
baseurl: /ai-code
permalink: /:year/:month/:title.html
defaults:
  - scope:
      path: ""
    values:
      layout: "post"
